env: 7dof-hit
agent:
    policy: exp-v03               
    seed: 0              
    start_timesteps: 200
    eval_freq: 1000
    max_timesteps: 5e7
    expl_noise: 0.1            
    batch_size: 256
    discount: 0.99             
    tau: 0.05
    policy_noise: 0.2             
    noise_clip: 0.5              
    policy_freq: 10       
    save_model: True     
    load_model: "default"               
    dump_dir : /run/media/luke/Data/uni/SS2023/DL Lab/Project/qualifying/DDPG_exp3
    file_name : ${agent.policy}_${env}_${agent.seed}